name: Build and deploy ASP.Net Core app to Azure Web App - ftask-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build -t myappimage -f Dockerfile .
          docker login ftaskdkregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker tag myappimage ftaskdkregistry.azurecr.io/myappimage:latest
          docker push ftaskdkregistry.azurecr.io/myappimage:latest

  
