name: Build and deploy ASP.Net Core app to Azure Web App - ftask-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build -t myappimage -f Dockerfile .
          docker login azure-container-registry-url -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker tag myappimage azure-container-registry-url/myappimage:latest
          docker push azure-container-registry-url/myappimage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: 'Production'
      url: ${{ secrets.WEBAPP_URL }}

    steps:
      - name: Deploy to Azure Web App from Container Registry
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'ftask-api'
          slot-name: 'Production'
          images: 'azure-container-registry-url/myappimage:latest'
          container-registry-url: 'azure-container-registry-url'
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
